Traceback (most recent call last):
  File "/home/giuk/.local/lib/python3.10/site-packages/concrete/fhe/compilation/module_compiler.py", line 405, in compile
    function.evaluate("Compiling", inputset, configuration, function_artifacts)
  File "/home/giuk/.local/lib/python3.10/site-packages/concrete/fhe/compilation/module_compiler.py", line 233, in evaluate
    self.trace(first_sample, artifacts)
  File "/home/giuk/.local/lib/python3.10/site-packages/concrete/fhe/compilation/module_compiler.py", line 146, in trace
    self.graph = Tracer.trace(self.function, parameters, location=self.location)
  File "/home/giuk/.local/lib/python3.10/site-packages/concrete/fhe/tracing/tracer.py", line 82, in trace
    output_tracers: Any = function(**arguments)
  File "/home/giuk/git5/concrete_ml/nsfw_detecct/module3.py", line 184, in classify
    indices = quantized_module.forward(image)
  File "/home/giuk/.local/lib/python3.10/site-packages/concrete/ml/quantization/quantized_module.py", line 457, in forward
    all_values_are_floats(*x),
  File "/home/giuk/.local/lib/python3.10/site-packages/concrete/ml/common/utils.py", line 570, in all_values_are_floats
    return all(_is_of_dtype(value, SUPPORTED_FLOAT_TYPES) for value in values)
  File "/home/giuk/.local/lib/python3.10/site-packages/concrete/ml/common/utils.py", line 570, in <genexpr>
    return all(_is_of_dtype(value, SUPPORTED_FLOAT_TYPES) for value in values)
  File "/home/giuk/.local/lib/python3.10/site-packages/concrete/ml/common/utils.py", line 439, in _is_of_dtype
    values_types = _get_dtype(values)
  File "/home/giuk/.local/lib/python3.10/site-packages/concrete/ml/common/utils.py", line 403, in _get_dtype
    return set(map(str, (values.dtype,)))
AttributeError: 'Tracer' object has no attribute 'dtype'
